#Set REMOTE_BROWSER_PLATFROM TO BS TO RUN ON BROWSERSTACK else
#SET REMOTE_BROWSER_PLATFORM TO SL TO RUN ON SAUCE LABS
REMOTE_BROWSER_PLATFORM = "BS"


USERNAME = "simaenduro1"
ACCESS_KEY = "C1gmgzXsxPAZ8qp16JGC"
